name: 'gh-action-hal-updater'
description: 'GitHub Action to pull publications from HAL and update them in a Hugo website'
author: 'Remy Chaput'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  author-id:
    description: 'The HAL AuthorID you want to get publications from.'
    required: true
  local-path:
    description: 'The path to the local folder containing publications.'
    required: true
  confidence-threshold:
    description: 'The minimum confidence to consider a candidate as a suitable match.'
    required: false
    default: "0.75"

runs:
  using: node20
  main: dist/index.js
